const fs = require('fs');
const path = require('path');

const ptBRPath = path.join(__dirname, '..', 'locales', 'pt-BR.json');
const enPath = path.join(__dirname, '..', 'locales', 'en.json');
const esPath = path.join(__dirname, '..', 'locales', 'es.json');

const ptBR = JSON.parse(fs.readFileSync(ptBRPath, 'utf8'));
const en = JSON.parse(fs.readFileSync(enPath, 'utf8'));
const es = JSON.parse(fs.readFileSync(esPath, 'utf8'));

const newPrivacyPt = {
    "intro": "Sua privacidade é muito importante para nós. Esta política descreve, de forma transparente e em conformidade com a Lei Geral de Proteção de Dados (LGPD — Lei nº 13.709/2018), como coletamos, usamos, armazenamos e protegemos suas informações pessoais no aplicativo Dualis.",
    "s1_title": "1. Informações que Coletamos",
    "s1_text": "Coletamos informações que você nos fornece diretamente, incluindo:",
    "s1_list": "<li><strong>Dados de cadastro:</strong> nome, e-mail, data de nascimento e senha.</li><li><strong>Informações do perfil:</strong> fotos, bio, igreja, interesses e gênero.</li><li><strong>Dados de fé:</strong> confissão religiosa (católica, evangélica, ortodoxa, etc.), ministério e denominação.</li><li><strong>Localização:</strong> cidade, estado, país e coordenadas geográficas (para mostrar pessoas próximas).</li><li><strong>Dados biométricos:</strong> selfie de verificação de identidade (quando solicitada pelo usuário).</li><li><strong>Dados técnicos:</strong> tipo de dispositivo, sistema operacional, token de notificação push e idioma do aparelho.</li>",
    "s1_footer": "Alguns desses dados são classificados como dados pessoais sensíveis pela LGPD, conforme detalhado na seção 2.",
    "s2_title": "2. Dados Pessoais Sensíveis (LGPD Art. 11)",
    "s2_intro": "Dado o caráter do aplicativo — um serviço de relacionamento voltado à comunidade cristã — processamos as seguintes categorias de dados pessoais sensíveis:",
    "s2_list": "<li>✝️ <strong>Crença religiosa:</strong> sua confissão de fé, denominação, igreja e nível de participação ministerial. Esses dados são essenciais para conectar você com pessoas de valores espirituais compatíveis.</li><li>👤 <strong>Gênero:</strong> informação utilizada exclusivamente para exibir perfis compatíveis de acordo com suas preferências de relacionamento.</li><li>📍 <strong>Geolocalização:</strong> coordenadas e cidade/estado são usados para mostrar pessoas próximas a você.</li><li>📸 <strong>Dados biométricos:</strong> a selfie de verificação de perfil é um dado biométrico processado apenas para confirmar que você corresponde às fotos do perfil.</li>",
    "s2_footer": "<strong>Base legal:</strong> Todos esses dados sensíveis são processados mediante seu consentimento explícito, conforme o Art. 11, inciso I da LGPD. Ao aceitar os Termos de Uso e Política de Privacidade no momento do cadastro, você consente de forma livre, informada e inequívoca com o tratamento desses dados para as finalidades descritas.<br><br><strong>Finalidade estrita:</strong> Esses dados são utilizados exclusivamente para operar o serviço de compatibilidade e conexão entre usuários, nunca sendo vendidos ou compartilhados com terceiros para fins de marketing ou publicidade.",
    "s3_title": "3. Como Usamos Seus Dados",
    "s3_intro": "Usamos suas informações para as seguintes finalidades:",
    "s3_list": "<li>Operar, manter e melhorar o serviço.</li><li>Conectar você com outros usuários compatíveis com base em fé, localização, idade e interesses.</li><li>Enviar notificações push e por e-mail (matches, curtidas, mensagens e atualizações do serviço).</li><li>Verificar identidade de perfis (selo de verificação).</li><li>Garantir a segurança da comunidade e prevenir fraudes.</li><li>Gerar estatísticas anônimas e agregadas para melhoria do serviço.</li><li>Cumprir obrigações legais e regulatórias.</li>",
    "s4_title": "4. Notificações Push",
    "s4_intro": "O Dualis pode enviar notificações push para o seu dispositivo, incluindo alertas de:",
    "s4_list": "<li>Novos matches (conexões recíprocas).</li><li>Curtidas recebidas ('olás').</li><li>Novas mensagens no chat.</li><li>Atualizações importantes do serviço.</li>",
    "s4_footer": "🔔 <strong>Ativação:</strong> As notificações push são ativadas mediante sua autorização durante o uso do aplicativo.<br><br>🔕 <strong>Desativação:</strong> Você pode desativar as notificações push a qualquer momento diretamente nas configurações do aplicativo (aba 'Config' → 'Receber Notificações Push'), sem necessidade de acessar as configurações do sistema operacional. A desativação das notificações não afeta o funcionamento do serviço.",
    "s5_title": "5. Notificações por E-mail",
    "s5_intro": "Ao criar sua conta no Dualis, você autoriza o envio de e-mails relacionados ao serviço, incluindo:",
    "s5_list": "<li>Notificações de novos matches e curtidas recebidas.</li><li>Alertas de mensagens não lidas.</li><li>Novidades e atualizações do aplicativo.</li><li>Comunicações de segurança da conta.</li>",
    "s5_footer": "📧 <strong>Cancelamento:</strong> Todos os e-mails promocionais e de notificação contêm um link de cancelamento de inscrição (unsubscribe) no rodapé. Ao clicar nesse link, você deixará de receber aquele tipo de comunicação por e-mail. E-mails essenciais de segurança da conta (redefinição de senha, alertas de segurança) continuarão sendo enviados conforme necessário.<br><br><strong>Base legal:</strong> O envio de e-mails de serviço é baseado no interesse legítimo do controlador (Art. 7, IX da LGPD) e na execução do contrato (Art. 7, V), com possibilidade de opt-out a qualquer momento.",
    "s6_title": "6. Compartilhamento de Informações",
    "s6_intro": "Não vendemos, alugamos ou comercializamos seus dados pessoais em nenhuma circunstância. Compartilhamos informações apenas:",
    "s6_list": "<li>Com provedores de infraestrutura essenciais para operar o serviço (hospedagem, armazenamento em nuvem, serviço de e-mail).</li><li>Quando exigido por lei, ordem judicial ou determinação de autoridade competente.</li><li>Para proteger os direitos, propriedade ou segurança do Dualis, de seus usuários ou do público.</li>",
    "s6_footer": "Todos os provedores terceirizados são obrigados contratualmente a proteger seus dados e a utilizá-los apenas para as finalidades especificadas.",
    "s7_title": "7. Segurança",
    "s7_intro": "Implementamos medidas técnicas e organizacionais de segurança para proteger seus dados pessoais, incluindo:",
    "s7_list": "<li>Criptografia de dados em trânsito (HTTPS/TLS).</li><li>Armazenamento seguro com controle de acesso.</li><li>Autenticação segura (hash de senhas).</li><li>Monitoramento contínuo de vulnerabilidades.</li>",
    "s7_footer": "No entanto, nenhum sistema de segurança é 100% infalível. Recomendamos que você mantenha sua senha segura e não a compartilhe com terceiros.",
    "s8_title": "8. Seus Direitos (LGPD Art. 18)",
    "s8_intro": "Em conformidade com o Art. 18 da LGPD, você tem os seguintes direitos sobre seus dados pessoais:",
    "s8_list": "<li>Confirmação da existência de tratamento dos seus dados.</li><li>Acesso aos dados pessoais que coletamos sobre você.</li><li>Correção de dados incompletos, inexatos ou desatualizados.</li><li>Anonimização, bloqueio ou eliminação de dados desnecessários ou excessivos.</li><li>Portabilidade dos dados a outro fornecedor de serviço.</li><li>Eliminação dos dados pessoais tratados com seu consentimento.</li><li>Informação sobre entidades com as quais seus dados são compartilhados.</li><li>Revogação do consentimento a qualquer momento.</li>",
    "s8_footer": "Você pode exercer a maioria desses direitos diretamente nas configurações do aplicativo (editar perfil, excluir conta). Para outros direitos, entre em contato com nosso DPO (seção 12).",
    "s9_title": "9. Verificação de Perfil",
    "s9_intro": "Oferecemos um sistema voluntário de verificação de identidade através de selfie com gesto. Ao solicitar verificação:",
    "s9_list": "<li>Você nos envia uma selfie realizando um gesto específico.</li><li>Comparamos a selfie com as fotos do seu perfil.</li><li>Se aprovado, seu perfil recebe um selo de verificação (ícone azul).</li><li>Se você alterar suas fotos após a verificação, o selo é removido automaticamente.</li>",
    "s9_footer": "A selfie de verificação (dado biométrico) é processada mediante seu consentimento explícito, armazenada de forma segura e utilizada exclusivamente para fins de verificação de identidade e prevenção a fraudes.<br><br>IMPORTANTE: O selo de verificação confirma apenas que a pessoa corresponde às fotos do perfil. NÃO garante caráter, intenções ou antecedentes do usuário.",
    "s10_title": "10. Isenção de Responsabilidade por Atos de Terceiros",
    "s10_intro": "O Dualis atua como plataforma intermediária para facilitar conexões entre usuários. Não realizamos verificação de antecedentes criminais, situação financeira, estado civil ou veracidade de todas as informações fornecidas pelos usuários.<br><br>⚠️ <strong>O DUALIS NÃO SE RESPONSABILIZA POR:</strong>",
    "s10_list1": "<li>Atos, condutas, declarações ou omissões de outros usuários.</li><li>Fraudes, golpes, enganos ou prejuízos financeiros decorrentes de interações com terceiros.</li><li>Danos morais, materiais ou psicológicos resultantes de encontros ou conversas entre usuários.</li>",
    "s10_mid": "🚫 <strong>NUNCA FORNEÇA A OUTROS USUÁRIOS:</strong>",
    "s10_list2": "<li>Documentos pessoais (RG, CPF, CNH, passaporte).</li><li>Dados bancários (número de conta, agência, senha).</li><li>Chaves PIX ou códigos de transferência.</li><li>Dinheiro, presentes ou valores em qualquer circunstância.</li><li>Senhas, códigos de verificação ou acesso a contas pessoais.</li>",
    "s10_footer": "Se alguém pedir qualquer um desses itens, denuncie imediatamente através do botão de denúncia no perfil do usuário. Sua segurança depende também da sua cautela. Para mais orientações, consulte nossas Dicas de Segurança.",
    "s11_title": "11. Retenção e Exclusão de Dados",
    "s11_intro": "Seus dados pessoais são mantidos enquanto sua conta estiver ativa no Dualis.",
    "s11_list": "<li><strong>Exclusão da conta:</strong> Você pode excluir sua conta a qualquer momento nas configurações do aplicativo (Perfil → Excluir Conta). Ao excluir sua conta, todos os seus dados pessoais, fotos, matches e conversas serão permanentemente removidos.</li><li><strong>Prazo de eliminação:</strong> Após a solicitação de exclusão, seus dados serão eliminados dos nossos sistemas em até 30 dias, exceto quando a retenção for necessária para cumprimento de obrigação legal ou regulatória.</li><li><strong>Dados anonimizados:</strong> Dados estatísticos agregados e anonimizados (que não permitem identificação pessoal) podem ser mantidos para fins de melhoria do serviço.</li>",
    "s12_title": "12. Contato do Encarregado de Dados (DPO)",
    "s12_text": "Para exercer seus direitos previstos na LGPD, revogar seu consentimento ou esclarecer dúvidas sobre o tratamento de seus dados pessoais, entre em contato com nosso Encarregado pelo Tratamento de Dados Pessoais (DPO) através do e-mail: <a href=\"mailto:dualis.love.app@gmail.com\" style=\"color: var(--accent);\">dualis.love.app@gmail.com</a>.<br><br>Prazo de resposta: Nos comprometemos a responder suas solicitações em até 15 dias úteis, conforme previsto na legislação."
};

const newPrivacyEn = {
    "intro": "Your privacy is very important to us. This policy describes, transparently and in compliance with the General Data Protection Law (LGPD — Law No. 13.709/2018), how we collect, use, store, and protect your personal information on the Dualis app.",
    "s1_title": "1. Information We Collect",
    "s1_text": "We collect information you provide directly to us, including:",
    "s1_list": "<li><strong>Registration data:</strong> name, email, date of birth, and password.</li><li><strong>Profile information:</strong> photos, bio, church, interests, and gender.</li><li><strong>Faith data:</strong> religious confession (Catholic, Evangelical, Orthodox, etc.), ministry, and denomination.</li><li><strong>Location:</strong> city, state, country, and geographical coordinates (to show people nearby).</li><li><strong>Biometric data:</strong> identity verification selfie (when requested by the user).</li><li><strong>Technical data:</strong> device type, operating system, push notification token, and device language.</li>",
    "s1_footer": "Some of this data is classified as sensitive personal data by the LGPD, as detailed in section 2.",
    "s2_title": "2. Sensitive Personal Data (LGPD Art. 11)",
    "s2_intro": "Given the nature of the application — a dating service aimed at the Christian community — we process the following categories of sensitive personal data:",
    "s2_list": "<li>✝️ <strong>Religious belief:</strong> your confession of faith, denomination, church, and level of ministerial participation. This data is essential to connect you with people of compatible spiritual values.</li><li>👤 <strong>Gender:</strong> information used exclusively to display compatible profiles according to your relationship preferences.</li><li>📍 <strong>Geolocation:</strong> coordinates and city/state are used to show people near you.</li><li>📸 <strong>Biometric data:</strong> the profile verification selfie is a biometric data processed solely to confirm that you match the profile photos.</li>",
    "s2_footer": "<strong>Legal basis:</strong> All of these sensitive data are processed with your explicit consent, pursuant to Art. 11, item I of the LGPD. By accepting the Terms of Use and Privacy Policy at the time of registration, you freely, informatively, and unequivocally consent to the processing of this data for the described purposes.<br><br><strong>Strict purpose:</strong> This data is used exclusively to operate the compatibility and connection service between users, never being sold or shared with third parties for marketing or advertising purposes.",
    "s3_title": "3. How We Use Your Data",
    "s3_intro": "We use your information for the following purposes:",
    "s3_list": "<li>Operate, maintain, and improve the service.</li><li>Connect you with other compatible users based on faith, location, age, and interests.</li><li>Send push and email notifications (matches, likes, messages, and service updates).</li><li>Verify profile identity (verification badge).</li><li>Ensure community security and prevent fraud.</li><li>Generate anonymous and aggregated statistics to improve the service.</li><li>Comply with legal and regulatory obligations.</li>",
    "s4_title": "4. Push Notifications",
    "s4_intro": "Dualis may send push notifications to your device, including alerts for:",
    "s4_list": "<li>New matches (reciprocal connections).</li><li>Received likes ('hellos').</li><li>New messages in chat.</li><li>Important service updates.</li>",
    "s4_footer": "🔔 <strong>Activation:</strong> Push notifications are activated upon your authorization while using the app.<br><br>🔕 <strong>Deactivation:</strong> You can deactivate push notifications at any time directly in the app settings (tab 'Config' → 'Receive Push Notifications'), without needing to access the operating system settings. Deactivating notifications does not affect the operation of the service.",
    "s5_title": "5. Email Notifications",
    "s5_intro": "By creating your account on Dualis, you authorize the sending of service-related emails, including:",
    "s5_list": "<li>Notifications of new matches and received likes.</li><li>Unread message alerts.</li><li>App news and updates.</li><li>Account security communications.</li>",
    "s5_footer": "📧 <strong>Cancellation:</strong> All promotional and notification emails contain an unsubscribe link in the footer. By clicking this link, you will stop receiving that type of communication by email. Essential account security emails (password reset, security alerts) will continue to be sent as necessary.<br><br><strong>Legal basis:</strong> Sending service emails is based on the legitimate interest of the controller (Art. 7, IX of the LGPD) and on the execution of the contract (Art. 7, V), with the possibility of opting out at any time.",
    "s6_title": "6. Information Sharing",
    "s6_intro": "We do not sell, rent, or trade your personal data under any circumstances. We share information only:",
    "s6_list": "<li>With essential infrastructure providers to operate the service (hosting, cloud storage, email service).</li><li>When required by law, court order, or determination of a competent authority.</li><li>To protect the rights, property, or safety of Dualis, its users, or the public.</li>",
    "s6_footer": "All third-party providers are contractually obligated to protect your data and to use it only for the specified purposes.",
    "s7_title": "7. Security",
    "s7_intro": "We implement technical and organizational security measures to protect your personal data, including:",
    "s7_list": "<li>Data encryption in transit (HTTPS/TLS).</li><li>Secure storage with access control.</li><li>Secure authentication (password hashing).</li><li>Continuous vulnerability monitoring.</li>",
    "s7_footer": "However, no security system is 100% infallible. We recommend that you keep your password secure and do not share it with third parties.",
    "s8_title": "8. Your Rights (LGPD Art. 18)",
    "s8_intro": "In accordance with Art. 18 of the LGPD, you have the following rights regarding your personal data:",
    "s8_list": "<li>Confirmation of the existence of the processing of your data.</li><li>Access to the personal data we collect about you.</li><li>Correction of incomplete, inaccurate, or outdated data.</li><li>Anonymization, blocking, or elimination of unnecessary or excessive data.</li><li>Data portability to another service provider.</li><li>Elimination of personal data processed with your consent.</li><li>Information about entities with which your data is shared.</li><li>Revocation of consent at any time.</li>",
    "s8_footer": "You can exercise most of these rights directly in the app settings (edit profile, delete account). For other rights, please contact our DPO (section 12).",
    "s9_title": "9. Profile Verification",
    "s9_intro": "We offer a voluntary identity verification system via a gesture selfie. When requesting verification:",
    "s9_list": "<li>You send us a selfie performing a specific gesture.</li><li>We compare the selfie with your profile photos.</li><li>If approved, your profile receives a verification badge (blue icon).</li><li>If you change your photos after verification, the badge is automatically removed.</li>",
    "s9_footer": "The verification selfie (biometric data) is processed upon your explicit consent, stored securely, and used exclusively for identity verification and fraud prevention purposes.<br><br>IMPORTANT: The verification badge only confirms that the person matches the profile photos. It DOES NOT guarantee the character, intentions, or background of the user.",
    "s10_title": "10. Disclaimer for Third-Party Acts",
    "s10_intro": "Dualis acts as an intermediary platform to facilitate connections between users. We do not conduct criminal background checks, financial status checks, marital status checks, or verify the truthfulness of all information provided by users.<br><br>⚠️ <strong>DUALIS IS NOT RESPONSIBLE FOR:</strong>",
    "s10_list1": "<li>Acts, conduct, statements, or omissions of other users.</li><li>Frauds, scams, deceptions, or financial losses resulting from interactions with third parties.</li><li>Moral, material, or psychological damages resulting from meetings or conversations between users.</li>",
    "s10_mid": "🚫 <strong>NEVER PROVIDE TO OTHER USERS:</strong>",
    "s10_list2": "<li>Personal documents (ID, passport, etc.).</li><li>Bank details (account number, branch, password).</li><li>PIX keys or transfer codes.</li><li>Money, gifts, or valuables under any circumstances.</li><li>Passwords, verification codes, or access to personal accounts.</li>",
    "s10_footer": "If anyone asks for any of these items, report them immediately via the report button on the user's profile. Your security also depends on your caution. For more guidance, consult our Safety Tips.",
    "s11_title": "11. Data Retention and Deletion",
    "s11_intro": "Your personal data is kept as long as your account is active on Dualis.",
    "s11_list": "<li><strong>Account deletion:</strong> You can delete your account at any time in the app settings (Profile → Delete Account). Upon deleting your account, all your personal data, photos, matches, and conversations will be permanently removed.</li><li><strong>Deletion timeframe:</strong> After the deletion request, your data will be eliminated from our systems within 30 days, except when retention is necessary to comply with legal or regulatory obligations.</li><li><strong>Anonymized data:</strong> Aggregated and anonymized statistical data (which does not allow personal identification) may be retained for service improvement purposes.</li>",
    "s12_title": "12. Contact the Data Protection Officer (DPO)",
    "s12_text": "To exercise your rights under the LGPD, revoke your consent, or clarify doubts regarding the processing of your personal data, contact our Data Protection Officer (DPO) via email: <a href=\"mailto:dualis.love.app@gmail.com\" style=\"color: var(--accent);\">dualis.love.app@gmail.com</a>.<br><br>Response time: We commit to responding to your requests within 15 business days, as required by law."
};

const newPrivacyEs = {
    "intro": "Su privacidad es muy importante para nosotros. Esta política describe, de manera transparente y en conformidad con la Ley General de Protección de Datos (LGPD — Ley Nº 13.709/2018), cómo recopilamos, usamos, almacenamos y protegemos su información personal en la aplicación Dualis.",
    "s1_title": "1. Información que Recopilamos",
    "s1_text": "Recopilamos la información que nos proporciona directamente, incluyendo:",
    "s1_list": "<li><strong>Datos de registro:</strong> nombre, correo electrónico, fecha de nacimiento y contraseña.</li><li><strong>Información del perfil:</strong> fotos, biografía, iglesia, intereses y género.</li><li><strong>Datos de fe:</strong> confesión religiosa (católica, evangélica, ortodoxa, etc.), ministerio y denominación.</li><li><strong>Ubicación:</strong> ciudad, estado, país y coordenadas geográficas (para mostrar personas cercanas).</li><li><strong>Datos biométricos:</strong> selfie de verificación de identidad (cuando lo solicite el usuario).</li><li><strong>Datos técnicos:</strong> tipo de dispositivo, sistema operativo, token de notificación push y el idioma del dispositivo.</li>",
    "s1_footer": "Algunos de estos datos se clasifican como datos personales confidenciales por la LGPD, como se detalla en la sección 2.",
    "s2_title": "2. Datos Personales Sensibles (LGPD Art. 11)",
    "s2_intro": "Dado el carácter de la aplicación — un servicio de citas dirigido a la comunidad cristiana — procesamos las siguientes categorías de datos personales sensibles:",
    "s2_list": "<li>✝️ <strong>Creencia religiosa:</strong> su confesión de fe, denominación, iglesia y nivel de participación ministerial. Estos datos son esenciales para conectarle con personas de valores espirituales compatibles.</li><li>👤 <strong>Género:</strong> información utilizada exclusivamente para mostrar perfiles compatibles según sus preferencias de relación.</li><li>📍 <strong>Geolocalización:</strong> las coordenadas y la ciudad/estado se utilizan para mostrarle personas cercanas a usted.</li><li>📸 <strong>Datos biométricos:</strong> el selfie de verificación de perfil es un dato biométrico procesado únicamente para confirmar que usted coincide con las fotos del perfil.</li>",
    "s2_footer": "<strong>Base legal:</strong> Todos estos datos sensibles son procesados mediante su consentimiento explícito, conforme al Art. 11, inciso I de la LGPD. Al aceptar los Términos de Uso y la Política de Privacidad en el momento del registro, usted consiente de forma libre, informada e inequívoca el tratamiento de estos datos para las finalidades descritas.<br><br><strong>Finalidad estricta:</strong> Estos datos se utilizan exclusivamente para operar el servicio de compatibilidad y conexión entre usuarios, no siendo nunca vendidos o compartidos con terceros para fines de marketing o publicidad.",
    "s3_title": "3. Cómo Usamos Sus Datos",
    "s3_intro": "Utilizamos su información para los siguientes fines:",
    "s3_list": "<li>Operar, mantener y mejorar el servicio.</li><li>Conectarlo con otros usuarios compatibles según la fe, ubicación, edad e intereses.</li><li>Enviar notificaciones push y por correo electrónico (matches, me gusta, mensajes y actualizaciones del servicio).</li><li>Verificar la identidad de los perfiles (insignia de verificación).</li><li>Garantizar la seguridad de la comunidad y prevenir el fraude.</li><li>Generar estadísticas anónimas y agregadas para la mejora del servicio.</li><li>Cumplir con las obligaciones legales y reglamentarias.</li>",
    "s4_title": "4. Notificaciones Push",
    "s4_intro": "Dualis puede enviar notificaciones push a su dispositivo, incluyendo alertas de:",
    "s4_list": "<li>Nuevos matches (conexiones recíprocas).</li><li>Me gusta recibidos ('holas').</li><li>Nuevos mensajes en el chat.</li><li>Actualizaciones importantes del servicio.</li>",
    "s4_footer": "🔔 <strong>Activación:</strong> Las notificaciones push se activan mediante su autorización durante el uso de la aplicación.<br><br>🔕 <strong>Desactivación:</strong> Puede desactivar las notificaciones push en cualquier momento directamente en la configuración de la aplicación (pestaña 'Config' → 'Recibir Notificaciones Push'), sin necesidad de acceder a la configuración del sistema operativo. La desactivación de las notificaciones no afecta el funcionamiento del servicio.",
    "s5_title": "5. Notificaciones por Correo Electrónico",
    "s5_intro": "Al crear su cuenta en Dualis, usted autoriza el envío de correos electrónicos relacionados con el servicio, incluyendo:",
    "s5_list": "<li>Notificaciones de nuevos matches y me gusta recibidos.</li><li>Alertas de mensajes no leídos.</li><li>Novedades y actualizaciones de la aplicación.</li><li>Comunicaciones sobre la seguridad de la cuenta.</li>",
    "s5_footer": "📧 <strong>Cancelación:</strong> Todos los correos electrónicos promocionales y de notificación contienen un enlace para darse de baja (unsubscribe) en el pie de página. Al hacer clic en este enlace, dejará de recibir ese tipo de comunicación por correo electrónico. Los correos electrónicos esenciales sobre la seguridad de la cuenta (restablecimiento de contraseña, alertas de seguridad) continuarán enviándose según sea necesario.<br><br><strong>Base legal:</strong> El envío de correos electrónicos de servicio se basa en el interés legítimo del controlador (Art. 7, IX de la LGPD) y en la ejecución del contrato (Art. 7, V), con la posibilidad de darse de baja en cualquier momento.",
    "s6_title": "6. Compartir Información",
    "s6_intro": "No vendemos, alquilamos ni comercializamos sus datos personales bajo ninguna circunstancia. Solo compartimos información:",
    "s6_list": "<li>Con proveedores de infraestructura esenciales para operar el servicio (hosting, almacenamiento en la nube, servicio de correo electrónico).</li><li>Cuando sea exigido por ley, orden judicial o determinación de una autoridad competente.</li><li>Para proteger los derechos, la propiedad o la seguridad de Dualis, de sus usuarios o del público.</li>",
    "s6_footer": "Todos los proveedores de terceros están obligados contractualmente a proteger sus datos y a utilizarlos únicamente para los fines especificados.",
    "s7_title": "7. Seguridad",
    "s7_intro": "Implementamos medidas técnicas y organizativas de seguridad para proteger sus datos personales, incluyendo:",
    "s7_list": "<li>Cifrado de datos en tránsito (HTTPS/TLS).</li><li>Almacenamiento seguro con control de acceso.</li><li>Autenticación segura (hash de contraseñas).</li><li>Monitoreo continuo de vulnerabilidades.</li>",
    "s7_footer": "Sin embargo, ningún sistema de seguridad es 100% infalible. Recomendamos que mantenga su contraseña segura y no la comparta con terceros.",
    "s8_title": "8. Sus Derechos (LGPD Art. 18)",
    "s8_intro": "De conformidad con el Art. 18 de la LGPD, usted tiene los siguientes derechos sobre sus datos personales:",
    "s8_list": "<li>Confirmación de la existencia del tratamiento de sus datos.</li><li>Acceso a los datos personales que recopilamos sobre usted.</li><li>Corrección de datos incompletos, inexactos o desactualizados.</li><li>Anonimización, bloqueo o eliminación de datos innecesarios o excesivos.</li><li>Portabilidad de los datos a otro proveedor de servicios.</li><li>Eliminación de los datos personales tratados con su consentimiento.</li><li>Información sobre las entidades con las cuales se comparten sus datos.</li><li>Revocación del consentimiento en cualquier momento.</li>",
    "s8_footer": "Puede ejercer la mayoría de estos derechos directamente en la configuración de la aplicación (editar perfil, eliminar cuenta). Para otros derechos, comuníquese con nuestro DPO (sección 12).",
    "s9_title": "9. Verificación de Perfil",
    "s9_intro": "Ofrecemos un sistema voluntario de verificación de identidad a través de un selfie con un gesto. Al solicitar la verificación:",
    "s9_list": "<li>Nos envía un selfie realizando un gesto específico.</li><li>Comparamos el selfie con sus fotos de perfil.</li><li>Si es aprobado, su perfil recibe una insignia de verificación (ícono azul).</li><li>Si cambia sus fotos después de la verificación, la insignia se elimina automáticamente.</li>",
    "s9_footer": "El selfie de verificación (dato biométrico) se procesa mediante su consentimiento explícito, se almacena de forma segura y se utiliza exclusivamente para fines de verificación de identidad y prevención de fraude.<br><br>IMPORTANTE: La insignia de verificación solo confirma que la persona coincide con las fotos del perfil. NO garantiza el carácter, las intenciones o los antecedentes del usuario.",
    "s10_title": "10. Exención de Responsabilidad por Actos de Terceros",
    "s10_intro": "Dualis actúa como una plataforma intermediaria para facilitar las conexiones entre los usuarios. No realizamos verificación de antecedentes penales, situación financiera, estado civil o veracidad de toda la información proporcionada por los usuarios.<br><br>⚠️ <strong>DUALIS NO SE RESPONSABILIZA POR:</strong>",
    "s10_list1": "<li>Actos, conductas, declaraciones u omisiones de otros usuarios.</li><li>Fraudes, estafas, engaños o pérdidas financieras resultantes de las interacciones con terceros.</li><li>Daños morales, materiales o psicológicos que resulten de encuentros o conversaciones entre usuarios.</li>",
    "s10_mid": "🚫 <strong>NUNCA PROPORCIONE A OTROS USUARIOS:</strong>",
    "s10_list2": "<li>Documentos personales (DNI, pasaporte).</li><li>Datos bancarios (número de cuenta, sucursal, contraseña).</li><li>Claves PIX o códigos de transferencia.</li><li>Dinero, regalos o valores bajo ninguna circunstancia.</li><li>Contraseñas, códigos de verificación o acceso a cuentas personales.</li>",
    "s10_footer": "Si alguien le pide alguno de estos elementos, repórtelo de inmediato a través del botón de denuncia en el perfil del usuario. Su seguridad también depende de su precaución. Para obtener más orientación, consulte nuestros Consejos de Seguridad.",
    "s11_title": "11. Retención y Eliminación de Datos",
    "s11_intro": "Sus datos personales se conservan mientras su cuenta esté activa en Dualis.",
    "s11_list": "<li><strong>Eliminación de la cuenta:</strong> Puede eliminar su cuenta en cualquier momento en la configuración de la aplicación (Perfil → Eliminar Cuenta). Al eliminar su cuenta, todos sus datos personales, fotos, matches y conversaciones se eliminarán de forma permanente.</li><li><strong>Plazo de eliminación:</strong> Después de la solicitud de eliminación, sus datos se eliminarán de nuestros sistemas en un plazo de 30 días, excepto cuando la retención sea necesaria para el cumplimiento de una obligación legal o regulatoria.</li><li><strong>Datos anonimizados:</strong> Los datos estadísticos agregados y anonimizados (que no permiten la identificación personal) pueden conservarse para fines de mejora del servicio.</li>",
    "s12_title": "12. Contacto del Oficial de Protección de Datos (DPO)",
    "s12_text": "Para ejercer sus derechos previstos en la LGPD, revocar su consentimiento o aclarar dudas sobre el tratamiento de sus datos personales, comuníquese con nuestro Oficial de Protección de Datos (DPO) a través del correo electrónico: <a href=\"mailto:dualis.love.app@gmail.com\" style=\"color: var(--accent);\">dualis.love.app@gmail.com</a>.<br><br>Plazo de respuesta: Nos comprometemos a responder a sus solicitudes en un plazo de 15 días hábiles, según lo previsto en la legislación."
};

ptBR.privacy = newPrivacyPt;
en.privacy = newPrivacyEn;
es.privacy = newPrivacyEs;

fs.writeFileSync(ptBRPath, JSON.stringify(ptBR, null, 4));
fs.writeFileSync(enPath, JSON.stringify(en, null, 4));
fs.writeFileSync(esPath, JSON.stringify(es, null, 4));

console.log('JSON files updated');
